name: digitalocean-hello-world
region: nyc
static_sites:
  - name: static-frontend
    github:
      repo: Tisicd/digitalocean-hello-world
      branch: main
      deploy_on_push: true
    source_dir: /
    build_command: ""
    run_command: ""
    output_dir: /
    routes:
      - path: /
    environment_slug: static-sites
    cors:
      allow_origins: ["*"]
      allow_methods: ["GET", "HEAD"]
      allow_headers: ["*"]

